### PR TITLE
Add Github Actions

### PR DESCRIPTION
**Pull request by kevin-bates**
This adds Github Actions since Travis appears to be gone.

Note:  I could not get the code coverage task to work.  If the task is uncommented, it will produce the following...

<details>
<summary>Run coveralls</summary>
<p>

```
  coveralls
  shell: /usr/bin/bash -e {0}
  env:
    TOX_ENV: py3.6
    pythonLocation: /opt/hostedtoolcache/Python/3.6.14/x64
    GITHUB_TOKEN: ***
Submitting coverage to coveralls.io...
Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
resubmitting with id None
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.14/x64/lib/python3.6/site-packages/coveralls/api.py", line 259, in submit_report
    response.raise_for_status()
  File "/opt/hostedtoolcache/Python/3.6.14/x64/lib/python3.6/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.14/x64/lib/python3.6/site-packages/coveralls/cli.py", line 93, in main
    result = coverallz.wear()
  File "/opt/hostedtoolcache/Python/3.6.14/x64/lib/python3.6/site-packages/coveralls/api.py", line 226, in wear
    return self.submit_report(json_string)
  File "/opt/hostedtoolcache/Python/3.6.14/x64/lib/python3.6/site-packages/coveralls/api.py", line 263, in submit_report
    'Could not submit coverage: {}'.format(e)) from e
coveralls.exception.CoverallsException: Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
Error: Process completed with exit code 1.
```

</p>
</details>

I suspect it has something to do with using the GH token to upload results.  Since I no little to nothing about both coveralls and github tokens, I'm hoping someone will have some tips to re-enable this.

### CODE REVIEW

**Comment by kevin-bates** [comment]
Hmm - I'm not sure why the actions are not running.  They ran on [my fork](https://github.com/kevin-bates/hadoop-yarn-api-python-client/actions).  Is there something we need to configure here?

**Comment by dimon222** [comment]
I think for coveralls I'm not allowed to grant any access as its being granted on organization level. (CODAIT in this case)
In terms of Github Actions overall - researching...

**Comment by dimon222** [comment]
Fixed coveralls, but for some reason I'm unable to trigger those actions on regular commit push. It only triggers for me on new branch creation. If I add commit and push it - no workflow is being triggered.

**Comment by kevin-bates** [comment]
Thank for you spending time on this @dimon222.  Looking at the actions tab on my fork's gh-action branch, the CI is completing successfully. 

Can you or @lresende go ahead and approve this PR so we can get some CI happening here?  Thanks.

**Pull request merged**
